name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        # copy or symlink libgtest.a and libgtest_main.a to your /usr/lib folder
        sudo cp *.a /usr/lib
    - name: configure
      run: cmake .
    - name: make
      run: make
    - name: test
      run: ./runtest
